baseURL: "http://TheBLOG-Site.com/"
languageCode: en-us
title: Home
theme : "PaperMod"

enableInlineShortcodes: true
enableEmoji: true # allowing using emoji
enableRobotsTXT: true
menu : 
  main: 
      - identifier: About
        name: About me
        url: /About
        weight: 1
      # - identifier: Projects
      #   name: Projects
      #   url : "/Projects/"
      #   weight: 2
      - identifier: Blogs
        name: Blogs 
        url: "/posts/"
        weight: 2

paginate: 15 # articles per page

params:
    profileMode:
        enabled: true
        title: "Mohd Rehan" # optional default will be site title
        subtitle: "M.L Enthusiast"
        imageUrl: "/ldcover.jpg" 
        imageTitle: "My Picture." # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Resume
            url: "https://drive.google.com/file/d/1zJ3iqyR-pI52q-1hhk-UooLyDZNMwCb7/view?usp=share_link"
    socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/mohd-rehan-3744b6194/"
        - name: "GitHub"
          url: "https://www.github.com/Reyan-786/"
        - name: "Quora"
          url: "https://www.quora.com/profile/Reyan-Abidin"
        - name: "Twitter"
          url: "https://twitter.com/AbidinReyan"
        - name: email
          url: "mailto:reyanabidin169@gmail.com"
        - name: instagram 
          url : "https://www.instagram.com/reyan_abidin_/"

